version: "3"
services:
  ruby-cf-bookbindery:
    image: ruby-cf-bookbindery
    container_name: ruby-cf-bookbindery
    build: .
    network_mode: bridge
    ports:
      - "4567:4567"
    volumes:
      - /<directory>/cf/docs-dev-guide:/tmp/docs-dev-guide